// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe4RfPAlhIvg7FbO-gBbu1qcms0Qi3ULw',
    appId: '1:107946950582:web:62b23f88eb15ebe1e04b17',
    messagingSenderId: '107946950582',
    projectId: 'todo-bae3d',
    authDomain: 'todo-bae3d.firebaseapp.com',
    storageBucket: 'todo-bae3d.appspot.com',
    measurementId: 'G-FNLMKQTMZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwG3WmIVh2gQs3jfRPSDr8X4jrFp8nmBE',
    appId: '1:107946950582:android:d0f7378a7b999034e04b17',
    messagingSenderId: '107946950582',
    projectId: 'todo-bae3d',
    storageBucket: 'todo-bae3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQyiHMx5pcGTQplMiayoOPcYpw4jGwy7E',
    appId: '1:107946950582:ios:1637da531f49faebe04b17',
    messagingSenderId: '107946950582',
    projectId: 'todo-bae3d',
    storageBucket: 'todo-bae3d.appspot.com',
    iosBundleId: 'com.tanvir.todo',
  );
}
